### ISSUE TITLE
Please help me.

### ISSUE THREAD

**Issue by Qianzujin** [danielmonettelli/MonettelliUIKIT#1]
![image](https://user-images.githubusercontent.com/49854479/81463306-43db2980-91eb-11ea-8a63-ee94740b79df.png)
![image](https://user-images.githubusercontent.com/49854479/81463317-57869000-91eb-11ea-9686-b7e0ff2a8622.png)

i've tried to solve this problem many times, but I still haven't compiled it successfully

-----I'm not very good at English

**Comment by Qianzujin** [comment]
I can't even preview these pictures

**Comment by Qianzujin** [comment]
I replaced the pictures, but the style was not right
![image](https://user-images.githubusercontent.com/49854479/81463471-78031a00-91ec-11ea-8761-b4a76b7c8d06.png)

**Comment by danielmonettelli** [comment]
Hello @Qianzujin , all the resources on Android must be in the "drawable" folder, I have tried the latest version of MonettelliUIKIT and it is working well, if you have the repository link it would help you better.

**Comment by Qianzujin** [comment]
I have installed the extension of vs2019 without using the repository link. I will try the code using the repository link again. Thank you very much!

**Comment by Qianzujin** [comment]
Yes, there is no problem with the code in the repository, but when I use the vs2019 template, the icon cannot be referenced normally


![image](https://user-images.githubusercontent.com/49854479/81468681-a0523f00-9213-11ea-8ea9-e1cda74c57c4.png)

**Comment by danielmonettelli** [comment]
Hello @Qianzujin , all FontIcons are created in "Icons.xaml", using the "FontImageSource" tag you can structure the appearance of your icon and implement it in the "Image" control or the "Icon" property of the "AppShell.xaml". For more information, you can view the official MonettelliUIKIT documentation https://danielmonettelli.github.io/MonettelliUIKITDOCS/.

## Interfaces
![image](https://i.pinimg.com/originals/1d/45/9d/1d459dde1df1cefb8a667df7ab41fb87.png)

## Shell
![image](https://i.pinimg.com/originals/5a/ee/af/5aeeaf4784d3cdc49a8b6bece566cc21.png)

**Comment by Qianzujin** [comment]
I solved this problem. I used the TTF file in the repository and replaced the TTF file in the vs2019 template, which was a success. I don't know why. Maybe the TTF file changed when vs2019 generated the template. I don't know why, but it works. Thank you for your help recently.
![image](https://user-images.githubusercontent.com/49854479/81497433-14aee000-92f1-11ea-9538-5f4d889d9568.png)


这是我最后一次尝试，没想到成功了，uwp的问题也是一样解决了。
This is my last attempt, but I didn't expect to succeed. The problem of uwp has also been solved

**Comment by Qianzujin** [comment]
![image](https://user-images.githubusercontent.com/49854479/81497480-5475c780-92f1-11ea-909e-113270b2c3ed.png)


Happy day！

**Comment by Qianzujin** [comment]
Today, I learned the function of this framework. TTF file is not a key issue. It's used for self configuration. It's designed very well. Thank you very much.

**Comment by Qianzujin** [comment]
Is there any MVVM framework available。。。。

**Comment by Qianzujin** [comment]
I tried to use some MVVM frameworks, but they didn't seem to support shell

**Comment by danielmonettelli** [comment]
Hi @Qianzujin , the MVVM frameworks are already working on the support.

**Comment by biapar** [comment]
> I tried to use some MVVM frameworks, but they didn't seem to support shell

this framework use MVVM Xamarin standard.

**Comment by danielmonettelli** [comment]
> this framework use MVVM Xamarin standard.

You can use the MVVM Framework of your preference.

**Comment by biapar** [comment]
Are there some app for example?
