### ISSUE TITLE
Do you have any update plans recently?

### ISSUE THREAD

**Issue by Qianzujin** [danielmonettelli/MonettelliUIKIT#2]
Do you have any update plans recently?

**Comment by Qianzujin** [comment]
emmm。。。 I've learned that Microsoft recently launched another Maui, which is based on. Net 6. Your project also contains similar features of Maui. In fact, I hope that this Microsoft Update will make xamarin's style more inclined to WPF's...

**Comment by danielmonettelli** [comment]
Hello @Qianzujin , MonettelliUIKIT I hope you also have support in the new .NET MAUI.

**Comment by Qianzujin** [comment]
Yes, I will continue to use it in the future
MonettelliUIKIT

thx

**Comment by danielmonettelli** [comment]
> Do you have any update plans recently?


I already released MonettelliUIKIT v3.0.0

**Comment by Qianzujin** [comment]
![image](https://user-images.githubusercontent.com/49854479/83727749-27aa9b00-a678-11ea-9cfa-1918ff697e56.png)
What a pity。。。

**Comment by Qianzujin** [comment]
I just think multi platform development is the charm of xamarin...

**Comment by danielmonettelli** [comment]
> I just think multi platform development is the charm of xamarin...

When they fix Embedded Fonts in UWP I will take it into account.

**Comment by Qianzujin** [comment]
It's true that Microsoft's multi platform has some flaws. For example, xamarin's navigation uwp and Android did not reach an agreement

There are other alternatives, but they take a lot of time and are not worth it.

Glad to discuss cross platform development with you

**Comment by Qianzujin** [comment]
I have seen your Netmaui-Chakramanta-app-Challenge project. Although Maui still has many bugs, I am looking forward to your work @danielmonettelli
