### ISSUE TITLE
Is there the template for Visual Studio for MAC?

### ISSUE THREAD

**Issue by biapar** [danielmonettelli/MonettelliUIKIT#4]
Is there the template for Visual Studio for MAC?

**Comment by danielmonettelli** [comment]
Hi @biapar , I'm working on it in the next updates.

**Comment by biapar** [comment]
So, at moment or copy and paste or create a new project on Windows and port on MAC

**Comment by danielmonettelli** [comment]
Hi @biapar, not necessarily, it can support you from GitHub or another platform that hosts repositories so you can work directly in VS for Mac.

**Comment by biapar** [comment]
Ok. I can download this https://github.com/MonettelliUIKIT/MonettelliUIKIT/tree/master/XF_Monettelli

**Comment by danielmonettelli** [comment]
That's right @biapar, but remember that VS for Mac Extensions  work with MonoDevelop.
