### ISSUE TITLE
How to made the row and columns colored without AdobeXD?

### ISSUE THREAD

**Issue by biapar** [danielmonettelli/MonettelliUIKIT#6]
How to made the row and columns colored without AdobeXD?
Maybe with Sketch?

**Comment by danielmonettelli** [comment]
Hello @biapar, you can do with any design tool that allows you to lower the opacity.

**Comment by biapar** [comment]
Ok. Sketch do. I read more time your blog. Finally, for you, the height of the page is always related to 1 or 100%. Then you divide the object height by height of the screen with a proportion... example  <height obj>:240 = 1:<height of the screen>

**Comment by danielmonettelli** [comment]
Hi @biapar, everything is on my blog.
